# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usera',
            name='herder',
            field=models.ImageField(default='static/images/default.jpg', upload_to='static/images/headers', verbose_name='用户头像'),
        ),
    ]
