# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20181021_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usera',
            old_name='herder',
            new_name='header',
        ),
    ]
