# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20181021_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usera',
            name='age',
            field=models.IntegerField(default=1, verbose_name='用户年龄'),
        ),
        migrations.AlterField(
            model_name='usera',
            name='gender',
            field=models.CharField(default=0, max_length=10, verbose_name='用户性别'),
        ),
    ]
